// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCqlvYJ6pH4BYtMcfpBcYEPPrFseXmrU',
    appId: '1:414573702316:web:01bc318e5484c75495c309',
    messagingSenderId: '414573702316',
    projectId: 'delivery-foodapp',
    authDomain: 'delivery-foodapp.firebaseapp.com',
    storageBucket: 'delivery-foodapp.appspot.com',
    measurementId: 'G-NCE3BQ02WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEXDjWH3kr1WILMfw93gw6MdFNnsj4c4',
    appId: '1:414573702316:android:e55907b2cecce81195c309',
    messagingSenderId: '414573702316',
    projectId: 'delivery-foodapp',
    storageBucket: 'delivery-foodapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0T5VW5sBhZvzZUqjG0gpR1MzUXK5v2w',
    appId: '1:414573702316:ios:c154f5b162aacefb95c309',
    messagingSenderId: '414573702316',
    projectId: 'delivery-foodapp',
    storageBucket: 'delivery-foodapp.appspot.com',
    iosClientId: '414573702316-5gkrcg2cfia8amq8o4vbash2b63vaud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lap9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd0T5VW5sBhZvzZUqjG0gpR1MzUXK5v2w',
    appId: '1:414573702316:ios:c154f5b162aacefb95c309',
    messagingSenderId: '414573702316',
    projectId: 'delivery-foodapp',
    storageBucket: 'delivery-foodapp.appspot.com',
    iosClientId: '414573702316-5gkrcg2cfia8amq8o4vbash2b63vaud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lap9',
  );
}
